# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y6yQdRYGYJP_d58WsXbDiK59Ml7I3u0A
"""

pip install streamlit

import streamlit as st

# 读取 HTML 文件
def load_map():
    with open('enhanced_malaysia_tourist_map.html', 'r', encoding='utf-8') as file:
        return file.read()

# Streamlit 界面
st.title("Interactive Map of Malaysian Tourist Attractions")
st.markdown("This is a map showing the tourist attractions in Malaysia. Explore by clicking the markers!")

# 显示 HTML 地图
html_map = load_map()
st.components.v1.html(html_map, height=800)